const express = require('express');
const service = require('./service');
const router = express.Router();
router.get('/', async (req,res,next)=>{try{res.render('customers/index',{title:'Customers',customers:await service.listCustomers(req.query),filters:req.query,options:await service.getFormOptions()});}catch(e){next(e);}});
router.get('/new', async (req,res,next)=>{try{res.render('customers/form',{title:'New Customer',customer:null,options:await service.getFormOptions()});}catch(e){next(e);}});
router.post('/', async (req,res,next)=>{try{const id=await service.createCustomer(req.body,req.session.user);res.redirect(req.app.locals.routePath(`/customers/${id}`));}catch(e){next(e);}});
router.get('/:id', async (req,res,next)=>{try{const customer=await service.getCustomerDetail(req.params.id);if(!customer)return res.status(404).send('Customer not found');res.render('customers/detail',{title:customer.display_name,customer,options:await service.getFormOptions()});}catch(e){next(e);}});
router.get('/:id/edit', async (req,res,next)=>{try{const customer=await service.getCustomerDetail(req.params.id);if(!customer)return res.status(404).send('Customer not found');res.render('customers/form',{title:`Edit ${customer.display_name}`,customer,options:await service.getFormOptions()});}catch(e){next(e);}});
router.post('/:id', async (req,res,next)=>{try{await service.updateCustomer(req.params.id,req.body,req.session.user);res.redirect(req.app.locals.routePath(`/customers/${req.params.id}`));}catch(e){next(e);}});
router.post('/:id/delete', async (req,res,next)=>{try{await service.deleteCustomer(req.params.id,req.session.user);res.redirect(req.app.locals.routePath('/customers'));}catch(e){next(e);}});
router.post('/:id/transition', async (req,res,next)=>{try{await service.transitionCustomer(req.params.id,req.body,req.session.user);res.redirect(req.app.locals.routePath(`/customers/${req.params.id}`));}catch(e){next(e);}});
router.post('/:id/work-orders', async (req,res,next)=>{try{const id=await service.createWorkOrderFromCustomer(req.params.id,req.body,req.session.user);res.redirect(req.app.locals.routePath(`/work-orders/${id}`));}catch(e){next(e);}});
router.post('/:id/pricing', async (req,res,next)=>{try{await service.upsertCustomerPricing(req.params.id,req.body,req.session.user);res.redirect(req.app.locals.routePath(`/customers/${req.params.id}`));}catch(e){next(e);}});
router.post('/:id/pricing/:pricingId/delete', async (req,res,next)=>{try{await service.deleteCustomerPricing(req.params.id,req.params.pricingId,req.session.user);res.redirect(req.app.locals.routePath(`/customers/${req.params.id}`));}catch(e){next(e);}});
router.post('/:id/notes', async (req,res,next)=>{try{await service.addNote(req.params.id,req.session.user?.id,req.body.note_body);res.redirect(req.app.locals.routePath(`/customers/${req.params.id}`));}catch(e){next(e);}});
module.exports = router;
