const express = require('express');
const techService = require('./service');
const workOrderService = require('../workOrders/service');
const router = express.Router();
router.get('/', (req, res) => res.redirect(req.app.locals.routePath('/tech/dashboard')));
router.get('/dashboard', async (req, res, next) => { try { res.render('tech/dashboard', { title: 'My Jobs', dashboard: await techService.getTechnicianDashboard(req.session.user.id) }); } catch (e) { next(e); } });
router.get('/work-orders/:id', async (req, res, next) => { try { const workOrder = await techService.getAssignedWorkOrderDetail(req.params.id, req.session.user); if (!workOrder) return res.status(404).send('Work order not found'); res.render('tech/work-order', { title: workOrder.title, workOrder }); } catch (e) { next(e); } });
router.post('/work-orders/:id/line-items', async (req, res, next) => { try { const workOrder = await techService.getAssignedWorkOrderDetail(req.params.id, req.session.user); if (!workOrder) return res.status(404).send('Work order not found'); await workOrderService.addLineItem(req.params.id, req.body); res.redirect(req.app.locals.routePath(`/tech/work-orders/${req.params.id}`)); } catch (e) { next(e); } });
router.post('/work-orders/:id/notes', async (req, res, next) => { try { const workOrder = await techService.getAssignedWorkOrderDetail(req.params.id, req.session.user); if (!workOrder) return res.status(404).send('Work order not found'); await workOrderService.addNote(req.params.id, req.session.user?.id, req.body.note_body); res.redirect(req.app.locals.routePath(`/tech/work-orders/${req.params.id}`)); } catch (e) { next(e); } });
router.post('/work-orders/:id/complete', async (req, res, next) => { try { const workOrder = await techService.getAssignedWorkOrderDetail(req.params.id, req.session.user); if (!workOrder) return res.status(404).send('Work order not found'); await workOrderService.transition(req.params.id, { action: 'complete', reason: req.body.reason || 'Completed from technician view' }, req.session.user); res.redirect(req.app.locals.routePath(`/tech/work-orders/${req.params.id}`)); } catch (e) { next(e); } });
module.exports = router;
